#!/usr/bin/env python3
"""Turn assets/patterns/index.json into assets/patterns/index.js.

The visuals page runs from file:// on the Pi, where fetch() of a file URL is
refused whatever flags Chromium was given. A <script> tag is not, so the index
travels as a script that assigns window.patternIndex rather than as JSON the
page would have to read. Run this once after the pattern assets are (re)synced:

    python tools/build-pattern-index.py            # from res/visuals

Neither index.json nor index.js is committed. assets/patterns/ is git-ignored
because the pattern licence allows on-screen use but not redistribution; this
script is the committed half of that arrangement, so a fresh checkout plus the
asset drop reproduces the index exactly.

Three things this adds to what index.json already says, all of them measured
from the files rather than assumed:

  wire    true when the artwork carries --occlusion-color, i.e. it is a solid
          3D form whose faces hide the edges behind them. patterns.js renders
          those with black faces and white strokes; everything else gets white
          faces and white strokes. Recolouring by alpha instead turns every
          occluded form into a white blob, which is what the first pass did.
  bytes   the total size of the seven frames, which is what the rasteriser's
          cost actually tracks; the `shapes` count in index.json is for the
          default frame only and the sweep can be five times heavier.
  frames  the seven file paths, sweep 0 to 5 then the default, with any
          degenerate frame replaced by its nearest usable neighbour. Nine
          patterns have a sweep frame 0 that is not artwork at all: with the
          slider at its minimum the site emits a 1591 byte paperclip icon,
          which would land on the screen as a paperclip.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PATTERNS = os.path.join(ROOT, 'assets', 'patterns')
SRC = os.path.join(PATTERNS, 'index.json')
DST = os.path.join(PATTERNS, 'index.js')

# Every real pattern export carries this class on its root <svg>. The
# placeholder icon does not, which is the only reliable way to tell them apart:
# the icon is also valid SVG and also has a viewBox.
MARK = 'svg-preview'


def read_head(path, n=4096):
    with open(path, encoding='utf-8') as f:
        return f.read(n)


def main():
    if not os.path.exists(SRC):
        sys.exit('no %s; the pattern assets are not in place' % SRC)
    with open(SRC, encoding='utf-8') as f:
        index = json.load(f)

    out = []
    dropped = []
    patched = 0
    for entry in index:
        slug = entry['slug']
        paths = list(entry['sweep']['files']) + [entry['file']]
        if len(paths) != 7:
            dropped.append((slug, 'expected 6 sweep frames, found %d' % (len(paths) - 1)))
            continue

        good = []
        for rel in paths:
            full = os.path.join(PATTERNS, rel.replace('/', os.sep))
            good.append(os.path.exists(full) and MARK in read_head(full))
        if not any(good):
            dropped.append((slug, 'no usable frame'))
            continue

        # Replace a degenerate frame with the nearest usable one, so the sweep
        # is still six frames and the morph simply flattens at that end.
        frames = []
        for i, rel in enumerate(paths):
            if good[i]:
                frames.append(rel)
                continue
            near = min((j for j in range(7) if good[j]), key=lambda j: abs(j - i))
            frames.append(paths[near])
            patched += 1

        total = 0
        for rel in set(frames):
            total += os.path.getsize(os.path.join(PATTERNS, rel.replace('/', os.sep)))

        default_head = read_head(os.path.join(PATTERNS, entry['file'].replace('/', os.sep)))
        out.append({
            'slug': slug,
            'title': entry.get('title', slug),
            'tags': entry.get('tags', []),
            'shapes': entry.get('shapes', 0),
            'bytes': total,
            'wire': '--occlusion-color' in default_head,
            'param': entry.get('sweep', {}).get('param', ''),
            'frames': frames,
        })

    body = json.dumps(out, separators=(',', ':'))
    with open(DST, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Generated by tools/build-pattern-index.py. Do not edit.\n')
        f.write('window.patternIndex = %s;\n' % body)

    print('%d patterns, %d frames patched, %d dropped -> %s'
          % (len(out), patched, len(dropped), DST))
    for slug, why in dropped:
        print('  dropped %s: %s' % (slug, why))
    wire = sum(1 for p in out if p['wire'])
    print('  %d wire (occluded faces), %d solid' % (wire, len(out) - wire))
    heavy = sorted(out, key=lambda p: -p['bytes'])[:5]
    print('  heaviest: %s' % ', '.join('%s %.1f MB' % (p['slug'], p['bytes'] / 1e6) for p in heavy))


if __name__ == '__main__':
    main()
