#!/usr/bin/env python3
"""List the clips in assets/video/ as assets/video/index.js.

The visuals page runs from file:// on the Pi, where fetch() of a file URL is
refused whatever flags Chromium was given, and cannot list a directory
either. A <script> tag is not refused, so the list travels as a script that
assigns window.videoIndex, exactly as the pattern index does:

    window.videoIndex = [{file, seconds, width, height}, ...]

`file` is relative to assets/video/, `seconds` is the duration ffprobe reports
and is what video.js picks a random start point inside. Run it from
res/visuals after adding or removing a clip (tools/prepare-video.py makes
them):

    python tools/build-video-index.py [--ffprobe PATH]

ffprobe is taken from PATH unless --ffprobe names it. Neither the clips nor
index.js is committed: assets/video/ is git-ignored because clips are usually
someone else's work, so they are deployed from the working tree by
deploy-skin.sh, which rsyncs res/.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VIDEO = os.path.join(ROOT, 'assets', 'video')
DST = os.path.join(VIDEO, 'index.js')
EXTS = ('.mp4', '.webm', '.m4v')


def probe(ffprobe, path):
    out = subprocess.run(
        [ffprobe, '-v', 'error', '-select_streams', 'v:0',
         '-show_entries', 'stream=width,height:format=duration', '-of', 'json', path],
        capture_output=True, text=True)
    if out.returncode != 0:
        return None, out.stderr.strip()
    data = json.loads(out.stdout)
    streams = data.get('streams') or []
    if not streams:
        return None, 'no video stream'
    try:
        seconds = float(data['format']['duration'])
    except (KeyError, ValueError):
        return None, 'no duration'
    return {'seconds': round(seconds, 2),
            'width': streams[0].get('width', 0),
            'height': streams[0].get('height', 0)}, None


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--ffprobe', default='ffprobe', help='ffprobe executable (default: from PATH)')
    args = ap.parse_args()

    ffprobe = shutil.which(args.ffprobe) or (args.ffprobe if os.path.exists(args.ffprobe) else None)
    if not ffprobe:
        sys.exit('no ffprobe at %r; put it on PATH or pass --ffprobe' % args.ffprobe)
    if not os.path.isdir(VIDEO):
        sys.exit('no %s; there are no clips' % VIDEO)

    out = []
    for name in sorted(os.listdir(VIDEO)):
        if not name.lower().endswith(EXTS):
            continue
        info, err = probe(ffprobe, os.path.join(VIDEO, name))
        if not info:
            print('  skipped %s: %s' % (name, err))
            continue
        out.append(dict(file=name, **info))

    body = json.dumps(out, separators=(',', ':'))
    with open(DST, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Generated by tools/build-video-index.py. Do not edit.\n')
        f.write('window.videoIndex = %s;\n' % body)

    print('%d clips -> %s' % (len(out), DST))
    for c in out:
        print('  %s  %.1f s  %dx%d' % (c['file'], c['seconds'], c['width'], c['height']))


if __name__ == '__main__':
    main()
