// The Book of Shapes pattern loader: SVG artwork off the disk, rasterised into
// hydra sources, with a sweep that the music morphs through.
//
// What is on disk. assets/patterns/ holds 54 patterns. Each one is
// `<slug>.svg`, the artwork at its default slider settings, plus
// `<slug>/<param>-<k>.svg` for k = 0..5, the same artwork swept along one
// slider from its minimum to its maximum. So a pattern is seven frames, and
// the sweep is a parameter animation somebody else already rendered: morphing
// between neighbouring frames is what makes a still SVG breathe.
// assets/patterns/index.js, generated by tools/build-pattern-index.py, is the
// catalogue. The assets are git-ignored because the licence covers on-screen
// use and not redistribution; the generator is committed, the output is not.
//
// Three things about these files that a first read of one does not show, all
// of them measured rather than assumed:
//
// 1. 370 of the 378 files have no `xmlns` on their root `<svg>`. Inline in an
//    HTML page that does not matter, because the HTML parser puts elements
//    into the SVG namespace itself. In an `<img>` the file is parsed as XML,
//    an element with no namespace is not SVG, and the image fails to load with
//    no error beyond `img.onerror`. Every frame here therefore goes through a
//    text rewrite before it is handed to an `<img>`, and the rewrite is why
//    XMLHttpRequest is in this file at all.
// 2. The artwork is coloured through CSS custom properties:
//    `fill="var(--fill-color, currentColor)"`, the same for `--stroke-color`,
//    and `--occlusion-color` with a literal `#1a1a1a` fallback on the hidden
//    faces of the 3D forms. Nothing defines those properties, so an untouched
//    file renders as black on transparent. The same rewrite that adds the
//    namespace defines the three properties, which is what makes these white
//    line work on black rather than a silhouette. Recolouring the rendered
//    alpha instead, which is the obvious route and the one tried first, works
//    for the 44 patterns that are pure line work and turns all 10 with
//    occluded faces into a solid white blob: iso-sphere's 11,232 cubes have
//    filled faces, and the alpha channel does not know a face from an edge.
//    `wire` in the index marks those 10, and they get black faces and white
//    strokes; everything else gets white faces and white strokes.
// 3. Eight patterns have a sweep frame 0 that is not artwork. With the slider
//    at its minimum the site emits a 1591 byte paperclip icon, and a paperclip
//    is exactly what the screen would show. The generator detects those (the
//    root `<svg>` of a real export carries `class="svg-preview"`) and repeats
//    the nearest usable frame in their place, so the sweep is always seven
//    frames and simply flattens at that end. Three of the eight never reach
//    the screen anyway, iso-sphere on size and backpack-grid and
//    masked_letter_grid on coverage, so five patterns in the rotation have a
//    flattened sweep end.
//
// Which patterns are in the rotation. Three rules, all below with their
// measurements. A pattern whose biggest single frame is over MAX_FRAME_BYTES
// is dropped before anything is fetched. A pattern whose default frame is lit
// past COVER_MAX is a filled sheet rather than line work. And a pattern whose
// measured worst animation frame is over WORST_FRAME_BUDGET_MS is retired,
// which is the only one of the three that depends on the hardware: the record
// is kept per slug in localStorage, so the Pi ends up with a smaller library
// than a desktop and neither has to be told which. On a desktop, 54 patterns
// on disk, 49 inside the size limit, 38 inside that and the coverage ceiling,
// and nothing retired on cost. Membership is otherwise decided on the default
// frame alone; the six sweep frames are measured and logged and gate nothing,
// so the morph always runs the whole sweep.
//
// Cost. Rasterising is not free and the heavy end of the library is very
// heavy: the timings are in the cost comment below. Nothing here
// rasterises on demand. A pattern is pulled into the cache in the background,
// no more than one frame every couple of animation frames and with the
// coverage readback in a frame of its own, so the main thread never stalls for
// longer than one SVG decode. A sketch only ever gets a pattern that is
// already sitting in memory: `take()` never blocks and returns null when the
// cache is empty, which the director treats exactly like a camera sketch with
// no camera.
//
// Memory. A frame is a 1024x1024 canvas, 4.19 MB of RGBA, so a pattern is
// 29.4 MB and the peak is three patterns, 88 MB, plus 16.8 MB of GPU memory
// for the four bound textures. Three is the peak and not the steady state
// only because prewarm() evicts down to two before it allocates the third; the
// first version pushed a fourth entry and trimmed afterwards, which was 117 MB
// for as long as the load took. That arithmetic is the reason CACHE_MAX is 3
// and not 10.
(function () {
  const BASE = 'assets/patterns/';
  const SIZE = 1024;
  const CACHE_MAX = 3;
  const PREWARM_MS = 20000;
  const PREWARM_DELAY_MS = 10000;  // quiet while the page finds its feet: the
                                   // first melt, the wordmark and the boot
                                   // logo all happen in the first seconds and
                                   // none of them should share a frame with an
                                   // SVG decode
  const FRAMES_PER_RASTER = 2;     // animation frames between one frame's draw
                                   // and the next one's
  const WORST_FRAME_BUDGET_MS = 120;  // see the cost map below
  const ROTATE_MS = 180000;  // a cached pattern nobody has shown for this long
                             // is fair game to replace, so a three hour set
                             // does not run on the first three patterns that
                             // happened to load
  const DEAD_BAND = 0.05;    // sweep positions either side of a frame boundary
                             // that keep the pair already bound

  // What a pattern costs, and what is done about it.
  //
  // Two filters, and they are different kinds of thing. The first is static
  // and is about file size: a pattern rasterises one frame every couple of
  // animation frames, so the seven-frame total is spread and the biggest
  // single frame is the stall. Measured on this desktop, the decode plus the
  // draw, both on the main thread:
  //
  //   pattern                 biggest frame   worst frame
  //   arcs_1                        0.03 MB         10 ms
  //   ripple_grid                   0.55 MB         74 ms
  //   resonance_field               1.50 MB         99 ms
  //   scattered-cube-grid           1.81 MB    212, 251 ms
  //   iso-cross                     1.93 MB        228 ms
  //   scattered-cube-grid-v3        2.56 MB        372 ms
  //   iso-sphere                    4.65 MB        608 ms
  //   deformed_grid_mesh_2          6.11 MB        597 ms
  //
  // 1.6 MB is where that table puts the cut, and it keeps the five patterns
  // nobody should attempt on any hardware out of the way before anything is
  // fetched.
  //
  // The second filter is the real one, and bytes are a poor proxy for it. The
  // Pi proved that twice over: concentric_arc_truchet_2 took 509 ms in its
  // worst frame there against 132 here, and noise_circle_1 took 225 ms on a
  // 137 KB frame, which is a worse cost per byte than patterns five times its
  // size. So the cost is not predicted from the file at all any more. Every
  // pattern is measured once, on the machine it is running on, and the result
  // is remembered: `{worstMs, when}` per slug in localStorage. A pattern whose
  // measured worst frame is over WORST_FRAME_BUDGET_MS is retired and is not
  // offered again; one that is over by more than double is evicted on the
  // spot as well, because it would otherwise hold the screen for a minute of a
  // set on a box that has just said it cannot afford it, while one that is
  // over by less is left in the cache it has already been rasterised into.
  //
  // A pattern nobody has measured stays eligible, which is what makes this
  // converge: every pattern is tried exactly once per profile, the affordable
  // set ends up the same whatever order they load in, and the cost of finding
  // out is one hitch per pattern per install rather than one per pattern per
  // boot. An earlier version ratcheted a byte cap down from the first pattern
  // that overran, which stranded most of the library behind whichever heavy
  // one happened to load first.
  //
  // 120 ms is three dropped frames at the page's 30 fps cap.
  //
  // A retirement is not forever. A record older than COST_STALE_MS is dropped
  // at startup and its pattern measured again, so a faster Chromium or a
  // quicker box brings the library back on its own rather than needing the
  // profile cleared.
  const MAX_FRAME_BYTES = 1.6e6;
  const COST_KEY = 'bitedj.patterns.cost';
  const COST_STALE_MS = 30 * 24 * 60 * 60 * 1000;   // 30 days

  // slug -> {worstMs, when}. localStorage is wrapped at both ends because a
  // page on file:// with a cleared profile can throw on either, and a loader
  // that throws at startup takes the whole family down with it.
  let cost = {};
  (function readCost() {
    let raw = null;
    try { raw = window.localStorage.getItem(COST_KEY); } catch (e) { raw = null; }
    if (!raw) return;
    try {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === 'object') cost = parsed;
    } catch (e) {
      cost = {};   // somebody else's data, or a truncated write
    }
  })();

  function writeCost() {
    try { window.localStorage.setItem(COST_KEY, JSON.stringify(cost)); } catch (e) { /* no storage */ }
  }

  function retired(slug) {
    const rec = cost[slug];
    return !!(rec && rec.worstMs > WORST_FRAME_BUDGET_MS);
  }

  // One sweep at startup rather than a check on every pick: an expired record
  // is deleted, and the pattern is then simply unmeasured again.
  (function expireCost() {
    const now = Date.now();
    let dropped = 0;
    Object.keys(cost).forEach(slug => {
      const rec = cost[slug];
      if (rec && rec.worstMs > WORST_FRAME_BUDGET_MS && now - rec.when > COST_STALE_MS) {
        delete cost[slug];
        dropped += 1;
        console.log('visuals: pattern', slug, 'cost record expired, measuring it again');
      }
    });
    if (dropped) writeCost();
  })();

  // The rewrite, in two halves.
  //
  // The root gets the namespace and the three colour properties. `<svg` is
  // always the first tag in these files and none of them carries a `style`
  // attribute on the root, so inserting after the four characters of the tag
  // name is safe. The eight files that do carry an `xmlns` are the
  // placeholder frames the generator has already replaced, but the guard
  // stays: a duplicate attribute is an XML error and would fail the whole
  // document.
  //
  // A `<style>` child then sets the stroke width, and that rule is the
  // difference between white line work and grey. 41 of the 54 patterns stroke
  // with `vector-effect="non-scaling-stroke"`, which means the width is in
  // device pixels at whatever size the file is rasterised, and the widths
  // they ask for run from 0.2 to 1. A stroke 0.5 px wide covers half a pixel
  // and arrives as a 50% grey, and no amount of raster size changes that: the
  // first version of this file tried to buy it back with
  // `filter: brightness(1.8)` on the draw, which lifts a 50% grey to about
  // 90% and cannot do better, because a brightness cannot widen a line. At
  // 2.5 px every stroke covers whole pixels and lands at 255 with an
  // antialiased edge either side.
  //
  // `vector-effect` is forced on as well, for the 13 patterns that do not ask
  // for it. Without it the width is in user units, and a user unit is 1024
  // divided by the viewBox: those 13 run from arcs_1's 259 units to
  // masked_letter_grid's 10,395, which is 3.95 px per unit at one end and 0.10
  // at the other. The same 2.5 would be a 9.9 px slab on the first and a
  // quarter of a pixel, invisible again, on the last. A CSS rule beats a
  // presentation attribute in the cascade whatever its specificity, which is
  // why this works on files that carry `stroke-width="0.5"` on every path.
  const STROKE_PX = 2.5;
  const RULE = '<style>*{vector-effect:non-scaling-stroke;stroke-width:'
    + STROKE_PX + 'px}</style>';

  const NS = 'xmlns="http://www.w3.org/2000/svg"';
  const WIRE = 'style="--fill-color:#000;--stroke-color:#fff;--occlusion-color:#000"';
  const SOLID = 'style="--fill-color:#fff;--stroke-color:#fff;--occlusion-color:#000"';

  const TAGS = ['GRID', 'RADIAL', 'NOISE', 'FLOW', 'ISOMETRIC', 'ORGANIC', 'DISTORTION', 'PHYSICS'];

  // The catalogue, after the static size filter. What is left of it is
  // narrowed again at pick time by the cost map, which moves: a pattern that
  // is eligible at boot is retired the moment it is measured over budget.
  const library = (window.patternIndex || []).filter(p => p.frame <= MAX_FRAME_BYTES);
  function eligible() {
    return library.filter(p => !retired(p.slug));
  }
  if (!window.patternIndex) {
    console.error('visuals: no pattern index; run tools/build-pattern-index.py');
  } else {
    console.log('visuals: patterns', eligible().length, 'eligible,',
      library.length - eligible().length, 'retired by measured cost;',
      library.length, 'of', window.patternIndex.length,
      'under the', (MAX_FRAME_BYTES / 1e6).toFixed(1) + ' MB frame size limit');
  }

  function svgDoc(text, wire) {
    const open = text.indexOf('<svg');
    if (open < 0) return null;
    const close = text.indexOf('>', open);
    if (close < 0) return null;   // a truncated file: no opening tag to close
    const head = text.slice(open, close);
    const add = (head.indexOf('xmlns') < 0 ? ' ' + NS : '') + ' ' + (wire ? WIRE : SOLID);
    return text.slice(0, open + 4) + add
      + text.slice(open + 4, close + 1) + RULE + text.slice(close + 1);
  }

  // n animation frames from now. The pacing in this file is all in frames
  // rather than milliseconds, because what it is trying not to do is put two
  // expensive things in the same frame as each other or as the render.
  function afterFrames(n, fn) {
    let left = n;
    const step = () => {
      left -= 1;
      if (left <= 0) fn(); else requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }

  // One frame: fetch the text, rewrite it, decode it through an <img>, and
  // draw it onto an opaque black canvas. The canvas is filled black first
  // rather than left transparent because hydra's blend() mixes rgb and ignores
  // alpha, and a source that is white everywhere with the artwork in its alpha
  // arrives on screen as a white slab; sketches.js says the same thing about
  // the wordmark at smear().
  //
  // Three pieces of main-thread work, and each gets its own animation frame:
  // the decode, which the browser does between `img.src` and `onload`; the
  // draw, FRAMES_PER_RASTER frames later; and the coverage readback, a frame
  // after that. The readback used to share the draw's frame, which was honest
  // about the total but made the stall the sum of two unrelated things. Split
  // apart, the worst single frame of a load is very nearly the decode alone,
  // which is the number the size cap is trying to control.
  function rasterise(path, wire, done) {
    let xhr;
    try {
      xhr = new XMLHttpRequest();
      xhr.open('GET', BASE + path, true);
    } catch (e) {
      console.error('visuals: pattern open failed', path, e);
      done(null); return;
    }
    xhr.onerror = () => { console.error('visuals: pattern fetch failed', path); done(null); };
    xhr.onload = () => {
      const doc = svgDoc(xhr.responseText || '', wire);
      if (!doc) { console.error('visuals: pattern has no <svg>', path); done(null); return; }
      const url = URL.createObjectURL(new Blob([doc], { type: 'image/svg+xml' }));
      const img = new Image();
      img.onerror = () => {
        URL.revokeObjectURL(url);
        console.error('visuals: pattern decode failed', path);
        done(null);
      };
      // The clock starts at the decode rather than at the draw. Both are on
      // the main thread and for the dense patterns the decode is the larger
      // half; only the XHR is somebody else's thread.
      let t0 = 0, decodeMs = 0;
      img.onload = () => {
        decodeMs = performance.now() - t0;
        afterFrames(FRAMES_PER_RASTER, () => {
          const t1 = performance.now();
          let cv = document.createElement('canvas');
          cv.width = SIZE; cv.height = SIZE;
          const ctx = cv.getContext('2d');
          ctx.fillStyle = '#000';
          ctx.fillRect(0, 0, SIZE, SIZE);
          try {
            ctx.drawImage(img, 0, 0, SIZE, SIZE);
          } catch (e) {
            console.error('visuals: pattern draw failed', path, e);
            cv = null;
          }
          URL.revokeObjectURL(url);
          const drawMs = decodeMs + (performance.now() - t1);
          if (!cv) { done(null); return; }
          afterFrames(1, () => {
            const t2 = performance.now();
            let lit = 0;
            try {
              lit = coverage(cv);
            } catch (e) {
              console.error('visuals: pattern coverage failed', path, e);
            }
            done(cv, drawMs, lit, performance.now() - t2);
          });
        });
      };
      t0 = performance.now();
      img.src = url;
    };
    xhr.send();
  }

  // How much of a frame is lit, 0 to 1, as a mean luminance. Drawing the
  // 1024x1024 canvas into a 64x64 one averages it in hardware, so this is 4096
  // pixels read back rather than a million.
  function coverage(cv) {
    const s = 64;
    const small = document.createElement('canvas');
    small.width = s; small.height = s;
    const c = small.getContext('2d', { willReadFrequently: true });
    c.drawImage(cv, 0, 0, s, s);
    const d = c.getImageData(0, 0, s, s).data;
    let sum = 0;
    for (let i = 0; i < d.length; i += 4) {
      sum += 0.2126 * d[i] + 0.7152 * d[i + 1] + 0.0722 * d[i + 2];
    }
    return sum / (255 * s * s);
  }

  // A ceiling on coverage, and nothing else. Some of this artwork is not line
  // work at any setting of its slider: it is a filled sheet with gaps in it,
  // and on screen it reads as a lit checkerboard rather than as drawing. The
  // default frame of every pattern was measured to set this, and at 0.30 the
  // eleven it removes are, in percent of the frame lit:
  //
  //   backpack-grid 66, concentric_arc_truchet_3 58, arcs_1 56,
  //   masked_letter_grid 51, isometric_ribbon_grid 45, hiding-squares 41,
  //   isometric_cubes 39, triangular_mosaic 39, modular_circle 34,
  //   quarter_circles_grid 34, resonance_field 32
  //
  // Nothing dense but linear is caught with them. The densest thing that stays
  // is flow_poles at 23, then nested_polygons_filled at 27 and rect_field_void
  // at 26, and the patterns this rule was most at risk of taking are nowhere
  // near it: wave-field 8, interference-mesh 10, node_garden 22, ripple_grid 5,
  // lissajous_field 5, and the iso wireframes between 5 and 10
  // (iso-cube-wireframe 6, isometric-cube-grid 6, iso_test_noise_field 7,
  // iso_test_noise_field_2 5, sine-cube 6, dna_helix 10). chaos_circles is the
  // close one at 29.6, and it stays: it is the artwork in the pattern-tint
  // screenshot that this ceiling exists to protect the look of.
  //
  // The default frame decides membership and it decides it alone. The sweep
  // frames are measured and logged but gate nothing, so a pattern whose slider
  // runs up into a solid sheet at one end stays in and morphs through it;
  // chaos_circles reaches 52 at the top of its own sweep. The whole 0 to 5
  // sweep is the morph range.
  //
  // An earlier version of this file had a floor as well, and a rule that
  // trimmed the degenerate ends off each sweep. Both went, because with the
  // strokes at their real width they were throwing away the dense line work
  // the show is built around, and only the ceiling is back.
  //
  // The test can only run after the pattern is rasterised, so a rejected
  // pattern costs one load, once, and then sits in `rejected` for the session.
  const COVER_MAX = 0.30;

  // The value of the brightest one percent of a frame, 0 to 255, over the
  // largest of the three channels rather than their luminance, because a
  // tinted line is still a lit line. This is the check that the stroke rule
  // above is working: a frame of half-pixel hairlines answers about 130, the
  // same artwork at 2.5 px answers 255. It reads a quarter of a million
  // pixels, which is why it runs once per pattern, on the default frame, and
  // not once per frame.
  function peak99(cv) {
    const d = cv.getContext('2d').getImageData(0, 0, SIZE, SIZE).data;
    const hist = new Uint32Array(256);
    let n = 0;
    for (let i = 0; i < d.length; i += 16) {
      hist[Math.max(d[i], d[i + 1], d[i + 2])] += 1;
      n += 1;
    }
    const cut = Math.max(1, Math.ceil(n * 0.01));
    let acc = 0;
    for (let v = 255; v >= 0; v--) {
      acc += hist[v];
      if (acc >= cut) return v;
    }
    return 0;
  }

  // 1x1, not dropped on the floor. A 1024x1024 backing store is not a JS
  // object and the heap is in no hurry about it, so every path that gives up
  // on a set of frames says so explicitly: the eviction in trim(), and the
  // partial load below, which would otherwise leave up to six full frames
  // behind on a fetch that failed on the seventh.
  function freeFrames(entry) {
    entry.frames.forEach(cv => { if (cv) { cv.width = 1; cv.height = 1; } });
  }

  // Seven frames, strictly one after another, so two patterns are never
  // rasterising into the same animation frames. Returns the entry it is
  // building, so a caller that gives up on the load can free what was built.
  function load(meta, done) {
    const entry = {
      meta: meta, frames: new Array(7), busy: true, ms: 0, worst: 0, peak: 0,
      cover: [], shownAt: 0, at: performance.now(), held: 0
    };
    let i = 0;
    (function step() {
      if (i >= 7) {
        // peak99() reads a quarter of a million pixels and gets a frame of its
        // own for the same reason the coverage readback does: landing it in
        // the same tick as the seventh raster made the worst frame of a load
        // the sum of two unrelated stalls, and the worst frame is the number
        // the budget is checked against.
        afterFrames(1, () => {
          const t0 = performance.now();
          entry.peak = peak99(entry.frames[6]);
          const peakMs = performance.now() - t0;
          entry.ms += peakMs;
          entry.worst = Math.max(entry.worst, peakMs);
          entry.busy = false;
          if (entry.cover[6] > COVER_MAX) {
            // Too solid to be line work; see COVER_MAX. The frames are freed
            // rather than kept, and the caller remembers the slug so the cost
            // is paid once a session and not once every twenty seconds.
            freeFrames(entry);
            console.log('visuals: pattern too solid', meta.slug,
              (100 * entry.cover[6]).toFixed(0) + '% of the default frame lit');
            done(null);
            return;
          }
          done(entry);
        });
        return;
      }
      rasterise(meta.frames[i], meta.wire, (cv, ms, lit, litMs) => {
        if (!cv) {
          entry.busy = false;
          freeFrames(entry);
          done(null);
          return;
        }
        entry.frames[i] = cv;
        entry.cover[i] = lit;
        // `worst` is the worst single animation frame, which is what the cap
        // is set against, so the draw and the readback count separately: they
        // are in different frames now and neither waits for the other.
        entry.ms += ms + litMs;
        entry.worst = Math.max(entry.worst, ms, litMs);
        i += 1;
        step();
      });
    })();
    return entry;
  }

  const cache = [];
  // Every slug shown this session. The prewarm steers around it, so a pattern
  // the room has never seen beats one that has already been round.
  const seen = [];
  const rejected = [];   // slugs whose load failed; never retried this session
  let loading = false;
  let tagTurn = 0;

  function cached(slug) {
    return cache.some(e => e.meta.slug === slug) || rejected.indexOf(slug) >= 0;
  }

  function pickFrom(pool) {
    return pool.length ? pool[Math.floor(Math.random() * pool.length)] : null;
  }

  // Which pattern to pull in next.
  //
  // The tag groups the ready set cannot answer for come first. take() prefers
  // a pattern whose tags match the sketch asking, and it can only do that if
  // the three patterns in memory between them cover more than one group, so
  // the prewarm's first job is to fill a hole rather than to deepen a group
  // that is already covered. After that it is a round robin over the eight
  // groups, which stops a run of prewarms landing three grids in a row just
  // because GRID is 21 of the 54 patterns.
  //
  // Inside whichever group it lands on, something never shown this session
  // beats something that has been round already, and the two fallbacks exist
  // because a prewarm that declines to load anything leaves the family with
  // whatever it has: first to a pattern already seen, then to any group at
  // all.
  function pickPrewarm() {
    const covered = Object.create(null);
    cache.forEach(e => {
      if (!e.busy) e.meta.tags.forEach(t => { covered[t] = true; });
    });
    const order = [];
    for (let n = 0; n < TAGS.length; n++) order.push(TAGS[(tagTurn + n) % TAGS.length]);
    const wanted = order.filter(t => !covered[t]).concat(order.filter(t => covered[t]));
    for (let n = 0; n < wanted.length; n++) {
      const tag = wanted[n];
      const pool = eligible().filter(p => p.tags.indexOf(tag) >= 0 && !cached(p.slug));
      const fresh = pool.filter(p => seen.indexOf(p.slug) < 0);
      const pick = pickFrom(fresh.length ? fresh : pool);
      if (pick) {
        tagTurn = (TAGS.indexOf(tag) + 1) % TAGS.length;
        return pick;
      }
    }
    const any = eligible().filter(p => !cached(p.slug));
    const fresh = any.filter(p => seen.indexOf(p.slug) < 0);
    return pickFrom(fresh.length ? fresh : any);
  }

  // Least recently shown first, and never one a sketch is currently drawing.
  // A resident that has been retired by the cost map goes before any of them,
  // whatever its age: take() will not hand it out again, so it is 29 MB of
  // nothing.
  function trim(limit) {
    const age = (e) => Math.max(e.shownAt, e.at);
    const dead = (e) => retired(e.meta.slug);
    while (cache.length > limit) {
      let worst = -1;
      for (let i = 0; i < cache.length; i++) {
        if (cache[i].held || cache[i].busy) continue;
        if (worst < 0) { worst = i; continue; }
        if (dead(cache[i]) !== dead(cache[worst])) {
          if (dead(cache[i])) worst = i;
        } else if (age(cache[i]) < age(cache[worst])) {
          worst = i;
        }
      }
      if (worst < 0) return;
      const gone = cache.splice(worst, 1)[0];
      freeFrames(gone);
      console.log('visuals: pattern evicted', gone.meta.slug);
    }
  }

  // Room in the cache, or a resident nobody has looked at for ROTATE_MS.
  //
  // One replacement per ROTATE_MS and no more. Without that clause a full
  // cache whose entries are all stale swaps one out every PREWARM_MS until
  // every one of them is new, and a run of three loads back to back is
  // measurable: the page dropped from 23 rendered frames a second to between
  // 12 and 17 while it was happening, and one smoothness sample taken across
  // it came out at four times the sketch's own figure.
  let lastSwapAt = 0;
  function hasRoom() {
    if (cache.length < CACHE_MAX) return true;
    const now = performance.now();
    if (now - lastSwapAt < ROTATE_MS) return false;
    return cache.some(e => !e.busy && !e.held && now - Math.max(e.shownAt, e.at) > ROTATE_MS);
  }

  // A load that never calls back would otherwise retire the whole family for
  // the session, because `loading` gates every later prewarm and nothing else
  // clears it. XMLHttpRequest on file:// has no timeout that can be relied on
  // and neither has image decoding, so the guard is a plain timer and a
  // generation counter: the abandoned load's callbacks, if they ever arrive,
  // see a stale generation and free what they built rather than joining the
  // cache behind the one that replaced them.
  //
  // The watchdog also frees the partial entry itself, which is up to six full
  // frames and 25 MB, and writes the slug into the cost map as an hour, so a
  // file that hangs once is not offered again on this profile. Waiting for the
  // abandoned callbacks to do that freeing is no good, because the whole point
  // of the watchdog is that they may never arrive.
  const LOAD_TIMEOUT_MS = 60000;
  let generation = 0;

  function prewarm() {
    if (loading || !hasRoom()) return;
    // Evict before allocating, not after. Pushing a fourth entry and trimming
    // afterwards is a second or two of four patterns in memory, 117 MB rather
    // than 88, at exactly the moment the page is also decoding an SVG. The
    // trim comes before the pick, so an entry that is about to be evicted does
    // not count as covering its tag group.
    trim(CACHE_MAX - 1);
    const meta = pickPrewarm();
    if (!meta) return;
    loading = true;
    if (cache.length >= CACHE_MAX - 1) lastSwapAt = performance.now();
    const t0 = performance.now();
    const mine = ++generation;
    let building = null;
    const watchdog = setTimeout(() => {
      if (generation !== mine) return;
      generation += 1;
      loading = false;
      if (building) freeFrames(building);
      cost[meta.slug] = { worstMs: LOAD_TIMEOUT_MS, when: Date.now(), why: 'timed out' };
      writeCost();
      rejected.push(meta.slug);
      console.log('visuals: pattern load timed out', meta.slug, 'retired');
      soon();
    }, LOAD_TIMEOUT_MS);
    building = load(meta, (entry) => {
      if (generation !== mine) {
        if (entry) freeFrames(entry);
        return;
      }
      clearTimeout(watchdog);
      loading = false;
      if (!entry) {
        // Either the load failed or the pattern is too solid; both are
        // properties of the artwork rather than of the moment, so neither is
        // retried.
        rejected.push(meta.slug);
        soon();
        return;
      }
      cache.push(entry);
      trim(CACHE_MAX);
      console.log('visuals: pattern ready', meta.slug,
        (performance.now() - t0).toFixed(0) + ' ms total,',
        entry.ms.toFixed(0) + ' ms on the main thread,',
        'worst frame ' + entry.worst.toFixed(0) + ' ms,',
        'peak ' + entry.peak + ',',
        'lit ' + entry.cover.slice(0, 6).map(c => (100 * c).toFixed(1)).join('/') + '%,',
        'default ' + (100 * entry.cover[6]).toFixed(1) + '%,',
        (meta.frame / 1e6).toFixed(2) + ' MB in its biggest frame');
      calibrate(entry);
    });
  }

  // A rejection leaves the cache one short, and waiting the full PREWARM_MS to
  // notice means twenty seconds of a smaller library for a load that cost
  // nothing to decide. Not instant, because a run of rejections back to back
  // would be a run of rasterises back to back, which is the thing the pacing
  // in this file exists to avoid. It cannot loop for ever: every rejection
  // removes a candidate permanently, so the supply of them is finite.
  const RETRY_MS = 2000;
  function soon() {
    setTimeout(prewarm, RETRY_MS);
  }

  // What the box actually did, written down so it is not discovered again.
  //
  // Every completed load records its worst single animation frame against the
  // slug, and a pattern whose record is over WORST_FRAME_BUDGET_MS is retired:
  // eligible() drops it, so neither the prewarm nor take() will offer it
  // again on this profile until the record goes stale. Over budget by more
  // than double and it is evicted on the spot as well, because it would
  // otherwise hold the screen for a minute of a set on a box that has just
  // said it cannot afford it; over by less and it stays in the cache it has
  // already been rasterised into, though take() will not hand it out, so it
  // leaves at the next eviction.
  //
  // An unmeasured pattern is always eligible. That is the whole design: every
  // pattern is tried exactly once per profile, the affordable set converges to
  // the same thing whatever order they load in, and the cost of finding out is
  // one hitch per pattern per install. The version before this ratcheted a
  // byte cap down from the first pattern that overran, which stranded most of
  // the library behind whichever heavy one happened to load first.
  function calibrate(entry) {
    const slug = entry.meta.slug;
    cost[slug] = { worstMs: Math.round(entry.worst), when: Date.now() };
    writeCost();
    if (entry.worst <= WORST_FRAME_BUDGET_MS) return;
    console.log('visuals: pattern', slug, 'over budget',
      entry.worst.toFixed(0), 'ms, retired');
    if (entry.worst > 2 * WORST_FRAME_BUDGET_MS) {
      const at = cache.indexOf(entry);
      if (at >= 0 && !entry.held) {
        cache.splice(at, 1);
        freeFrames(entry);
        console.log('visuals: pattern evicted', slug,
          'over the frame budget by more than double');
      }
    }
    soon();
  }

  // The first prewarm waits. A page that has just loaded is drawing its first
  // melt out of a blank still and building the wordmark texture, and an SVG
  // decode landing in the same frames as that is the one hitch a viewer is
  // guaranteed to see, because it is the only one they are already looking at
  // the screen for.
  setTimeout(() => {
    prewarm();
    setInterval(prewarm, PREWARM_MS);
  }, PREWARM_DELAY_MS);

  // The sweep clock. A full traverse of the six frames takes about 40 s when
  // the room is quiet and about 12 s when it is loud, and the position is
  // 2.5 + 2.5 sin(phase), so the pattern breathes through its parameter and
  // back rather than snapping round at the end. Like flow() in sketches.js
  // this integrates a rate rather than multiplying a clock: multiplying an
  // absolute time by feed.energy walks the picture backwards every time the
  // room gets quieter.
  //
  // The swell then pushes the position toward the top of the sweep, so a loud
  // passage sits in the dense half of the parameter and a break sits in the
  // sparse half. It is applied to the 0..1 position and pulls toward 1, which
  // cannot take the result out of range whatever the swell does.
  let phase = 0, phaseAt = performance.now();
  function sweepTick() {
    const now = performance.now();
    const dt = Math.min(100, now - phaseAt);
    phaseAt = now;
    const energy = window.feed ? feed.energy : 0;
    phase += Math.PI * dt / (40000 - 28000 * energy);
    if (phase > 2 * Math.PI) phase -= 2 * Math.PI;
    requestAnimationFrame(sweepTick);
  }
  requestAnimationFrame(sweepTick);

  function sweepT() {
    const u = 0.5 * (1 + Math.sin(phase));
    const swell = window.feed ? feed.swell : 0;
    return 5 * (u + 0.35 * swell * (1 - u));
  }

  // Two slots, so a sketch can hold two patterns at once: slot 0 is s4 and s5,
  // slot 1 is s6 and s7. The melt owns s3 and sketches own nothing below s4.
  const slots = [
    { a: null, b: null, entry: null, i0: -1, i1: -1 },
    { a: null, b: null, entry: null, i0: -1, i1: -1 }
  ];
  const mix = [0, 0];

  // init() builds a fresh regl texture and drops the old one on the floor, so
  // the previous one is destroyed here by hand. Without this a set's worth of
  // frame changes, one every two to four seconds, is a few gigabytes of GPU
  // memory nobody ever asked for.
  function upload(source, canvas) {
    // A canvas an eviction has already shrunk is not a frame. Leaving the
    // previous texture bound shows a stale frame, which is a morph that
    // pauses; uploading a 1x1 would fill the screen with one pixel of it.
    if (!source || !canvas || canvas.width !== SIZE) return;
    try { if (source.tex && source.tex.destroy) source.tex.destroy(); } catch (e) { /* regl kept it */ }
    source.init({ src: canvas, dynamic: false });
  }

  function bindFrames(entry, i0, i1, f, slot) {
    slot = slot ? 1 : 0;
    mix[slot] = Math.max(0, Math.min(1, f));
    if (!entry || entry.busy) return;
    const st = slots[slot];
    if (st.entry === entry && st.i0 === i0 && st.i1 === i1) return;
    const sa = slot ? (window.s6 || null) : (window.s4 || null);
    const sb = slot ? (window.s7 || null) : (window.s5 || null);
    upload(sa, entry.frames[i0]);
    upload(sb, entry.frames[i1]);
    if (st.entry && st.entry !== entry) st.entry.held -= 1;
    if (st.entry !== entry) entry.held += 1;
    st.entry = entry; st.i0 = i0; st.i1 = i1;
  }

  window.patterns = {
    mix: mix,
    // What has been measured, for the load test and for anyone reading the
    // log and wondering why the library shrank.
    get retired() { return library.filter(p => retired(p.slug)).length; },
    cost() { return cost; },
    get count() { return eligible().length; },

    ready() {
      return cache.some(e => !e.busy);
    },

    // A ready pattern for a sketch that wants one of `tags`. Never blocks,
    // never rasterises, and returns null only when nothing has finished
    // loading.
    //
    // Two tiers: a pattern whose tags match, least recently shown first, and
    // failing that any ready pattern, least recently shown first.
    //
    // There were four for a while, with a "not shown in the last eight picks"
    // test in front of each of these, and two of them could never fire. The
    // cache holds three patterns and the recency list held the last eight
    // picks, so after the first few switches every cached pattern was in it
    // and the unshown tiers were always empty; when they were not empty, the
    // least-recently-shown sort picked the same entry anyway. What actually
    // stops one artwork coming up under sketch after sketch is the two things
    // left: the tag comes first, so a sketch is choosing between the patterns
    // that suit it rather than the whole cache, and pickPrewarm() fills the
    // tag groups the cache cannot answer for, so that choice has more than one
    // candidate in it.
    take(tags, exclude) {
      const pool = cache.filter(e => !e.busy && e !== exclude && !retired(e.meta.slug));
      if (!pool.length) return null;
      const byAge = (a, b) => a.shownAt - b.shownAt;
      const want = tags && tags.length ? tags : [];
      const tagged = want.length
        ? pool.filter(e => e.meta.tags.some(t => want.indexOf(t) >= 0))
        : [];
      const from = tagged.length ? tagged : pool;
      const pick = from.slice().sort(byAge)[0];
      pick.shownAt = performance.now();
      if (seen.indexOf(pick.meta.slug) < 0) seen.push(pick.meta.slug);
      return pick;
    },

    // 0..5 along the sweep, advancing on its own clock.
    sweepT: sweepT,

    // Put frames floor(t) and ceil(t) on the slot's two sources and record the
    // fraction for the chain's blend(). Only re-uploads when the integer part
    // moves, which is every two to four seconds, not every frame.
    //
    // DEAD_BAND is why the integer part is not simply floor(t). The sweep
    // position is a sine, so it stops and reverses, and it can stop within a
    // hundredth of an integer: every rendered frame the position crosses the
    // boundary is then two texture uploads, 8 MB of them, and a position
    // hovering there does that thirty times a second. Inside the band the
    // pair already bound is kept and the fraction is clamped, which is the
    // same picture, because at the boundary the mix is showing one frame
    // whichever pair it is expressed in.
    bind(entry, t, slot) {
      if (!entry) return;
      const tt = Math.max(0, Math.min(5, t));
      const st = slots[slot ? 1 : 0];
      let i0 = Math.min(4, Math.floor(tt));
      if (st.entry === entry && st.i1 === st.i0 + 1
        && tt > st.i0 - DEAD_BAND && tt < st.i1 + DEAD_BAND) {
        i0 = st.i0;
      }
      bindFrames(entry, i0, i0 + 1, tt - i0, slot);
    },

    // The two ends a sketch might want by name rather than by position: the
    // frame the site's own default settings drew, which is index 6 and is not
    // part of the sweep at all, and the top of the sweep.
    base() { return 6; },
    top() { return 5; },

    // The primitive under bind(), for a sketch that wants two frames that are
    // not neighbours: pattern-melt crossfades the default against the top of
    // the sweep.
    bindFrames: bindFrames,

    // The director calls this on every sketch switch, before run(). A pattern
    // is only protected from eviction while a sketch is drawing it: the bound
    // GPU textures are copies and survive the canvas being freed, so the hold
    // exists for the next bind() and nothing else. Without the release the two
    // slots would pin two of the three cache entries for ever.
    release() {
      slots.forEach(st => {
        if (st.entry) st.entry.held = Math.max(0, st.entry.held - 1);
        st.entry = null; st.i0 = -1; st.i1 = -1;
      });
    },

    // For the load test and the memory measurement.
    stats() {
      return cache.map(e => ({
        slug: e.meta.slug, busy: e.busy, ms: Math.round(e.ms),
        worst: Math.round(e.worst), peak: e.peak,
        lit: e.cover.slice(0, 6).map(c => +(100 * c).toFixed(1)),
        mb: +(e.meta.frame / 1e6).toFixed(2), held: e.held
      }));
    }
  };
})();
