// The Book of Shapes pattern loader: SVG artwork off the disk, rasterised into
// hydra sources, with a sweep that the music morphs through.
//
// What is on disk. assets/patterns/ holds 54 patterns. Each one is
// `<slug>.svg`, the artwork at its default slider settings, plus
// `<slug>/<param>-<k>.svg` for k = 0..5, the same artwork swept along one
// slider from its minimum to its maximum. So a pattern is seven frames, and
// the sweep is a parameter animation somebody else already rendered: morphing
// between neighbouring frames is what makes a still SVG breathe.
// assets/patterns/index.js, generated by tools/build-pattern-index.py, is the
// catalogue. The assets are git-ignored because the licence covers on-screen
// use and not redistribution; the generator is committed, the output is not.
//
// Three things about these files that a first read of one does not show, all
// of them measured rather than assumed:
//
// 1. 370 of the 378 files have no `xmlns` on their root `<svg>`. Inline in an
//    HTML page that does not matter, because the HTML parser puts elements
//    into the SVG namespace itself. In an `<img>` the file is parsed as XML,
//    an element with no namespace is not SVG, and the image fails to load with
//    no error beyond `img.onerror`. Every frame here therefore goes through a
//    text rewrite before it is handed to an `<img>`, and the rewrite is why
//    XMLHttpRequest is in this file at all.
// 2. The artwork is coloured through CSS custom properties:
//    `fill="var(--fill-color, currentColor)"`, the same for `--stroke-color`,
//    and `--occlusion-color` with a literal `#1a1a1a` fallback on the hidden
//    faces of the 3D forms. Nothing defines those properties, so an untouched
//    file renders as black on transparent. The same rewrite that adds the
//    namespace defines the three properties, which is what makes these white
//    line work on black rather than a silhouette. Recolouring the rendered
//    alpha instead, which is the obvious route and the one tried first, works
//    for the 44 patterns that are pure line work and turns all 10 with
//    occluded faces into a solid white blob: iso-sphere's 11,232 cubes have
//    filled faces, and the alpha channel does not know a face from an edge.
//    `wire` in the index marks those 10, and they get black faces and white
//    strokes; everything else gets white faces and white strokes.
// 3. Eight patterns have a sweep frame 0 that is not artwork. With the slider
//    at its minimum the site emits a 1591 byte paperclip icon, and a paperclip
//    is exactly what the screen would show. The generator detects those (the
//    root `<svg>` of a real export carries `class="svg-preview"`) and repeats
//    the nearest usable frame in their place, so the sweep is always seven
//    frames and simply flattens at that end. One of the eight is iso-sphere,
//    which the size limit below keeps out of the rotation anyway, so seven
//    patterns on screen have a flattened sweep end.
//
// Cost. Rasterising is not free and the heavy end of the library is very
// heavy: the timings are in the size limit comment below. Nothing here
// rasterises on demand. A pattern is pulled into the cache in the background,
// one frame per animation frame so the main thread never stalls for longer
// than a single frame's draw, and a sketch only ever gets a pattern that is
// already sitting in memory. `take()` never blocks and returns null when the
// cache is empty, which the director treats exactly like a camera sketch with
// no camera.
//
// Memory. A frame is a 1024x1024 canvas, 4.19 MB of RGBA, so a pattern is
// 29.4 MB and the peak is three patterns, 88 MB, plus 16.8 MB of GPU memory
// for the four bound textures. Three is the peak and not the steady state
// only because prewarm() evicts down to two before it allocates the third; the
// first version pushed a fourth entry and trimmed afterwards, which was 117 MB
// for as long as the load took. That arithmetic is the reason CACHE_MAX is 3
// and not 10.
(function () {
  const BASE = 'assets/patterns/';
  const SIZE = 1024;
  const CACHE_MAX = 3;
  const PREWARM_MS = 20000;
  const ROTATE_MS = 180000;  // a cached pattern nobody has shown for this long
                             // is fair game to replace, so a three hour set
                             // does not run on the first three patterns that
                             // happened to load
  const RECENT = 8;          // slugs take() steers around, one per sketch in
                             // the family, so a full round of them can only
                             // repeat an artwork once the cache has nothing
                             // else to offer
  const DEAD_BAND = 0.05;    // sweep positions either side of a frame boundary
                             // that keep the pair already bound

  // What a pattern costs, and what the size limit is a limit on.
  //
  // The number to hold a limit against is the biggest single frame, not the
  // seven-frame total. A pattern rasterises one frame per animation frame, so
  // the total is spread and the biggest frame is the stall: at the page's
  // 30 fps cap, 250 ms is seven dropped frames in a row, and the Pi is roughly
  // four times slower again. The generator puts both figures in the index and
  // this gates on `frame`.
  //
  // Measured here at 1024x1024, the decode plus the draw plus the coverage
  // readback, all of them on the main thread and all inside the timed block:
  //
  //   pattern                 biggest frame   worst frame
  //   arcs_1                        0.03 MB         10 ms
  //   ripple_grid                   0.55 MB         74 ms
  //   resonance_field               1.50 MB         99 ms
  //   scattered-cube-grid           1.81 MB    212, 251 ms
  //   iso-cross                     1.93 MB        228 ms
  //   scattered-cube-grid-v3        2.56 MB        372 ms
  //   iso-sphere                    4.65 MB        608 ms
  //   deformed_grid_mesh_2          6.11 MB        597 ms
  //
  // 1.6 MB a frame is the cut. It is not the largest number that ever came in
  // under 250 ms: scattered-cube-grid at 1.81 MB measured 212 ms on one run
  // and 251 ms on another, which is a pattern sitting on the ceiling rather
  // than under it, and the same is true of iso-cross. Below 1.6 MB the worst
  // anything measured was 99 ms, which leaves room for a slower box and for
  // the run to run spread. It keeps 49 of the 54 patterns.
  //
  // The whole table is about twice what these same patterns cost before the
  // stroke rule below went in, which is the price of white line work: 2.5 px
  // of stroke is five times the fill of half a pixel. The `worst frame` figure
  // is logged at the end of every load, so the cut can be re-derived on the Pi
  // rather than assumed from this table.
  const MAX_FRAME_BYTES = 1.6e6;

  // The rewrite, in two halves.
  //
  // The root gets the namespace and the three colour properties. `<svg` is
  // always the first tag in these files and none of them carries a `style`
  // attribute on the root, so inserting after the four characters of the tag
  // name is safe. The eight files that do carry an `xmlns` are the
  // placeholder frames the generator has already replaced, but the guard
  // stays: a duplicate attribute is an XML error and would fail the whole
  // document.
  //
  // A `<style>` child then sets the stroke width, and that rule is the
  // difference between white line work and grey. 41 of the 54 patterns stroke
  // with `vector-effect="non-scaling-stroke"`, which means the width is in
  // device pixels at whatever size the file is rasterised, and the widths
  // they ask for run from 0.2 to 1. A stroke 0.5 px wide covers half a pixel
  // and arrives as a 50% grey, and no amount of raster size changes that: the
  // first version of this file tried to buy it back with
  // `filter: brightness(1.8)` on the draw, which lifts a 50% grey to about
  // 90% and cannot do better, because a brightness cannot widen a line. At
  // 2.5 px every stroke covers whole pixels and lands at 255 with an
  // antialiased edge either side.
  //
  // `vector-effect` is forced on as well, for the 13 patterns that do not ask
  // for it: without it the width is in user units and scales by the viewBox,
  // which is between 2 and 20 here, so the same rule would give one pattern a
  // 5 px stroke and another a 50 px one. A CSS rule beats a presentation
  // attribute in the cascade whatever its specificity, which is why this works
  // on files that carry `stroke-width="0.5"` on every path.
  const STROKE_PX = 2.5;
  const RULE = '<style>*{vector-effect:non-scaling-stroke;stroke-width:'
    + STROKE_PX + 'px}</style>';

  const NS = 'xmlns="http://www.w3.org/2000/svg"';
  const WIRE = 'style="--fill-color:#000;--stroke-color:#fff;--occlusion-color:#000"';
  const SOLID = 'style="--fill-color:#fff;--stroke-color:#fff;--occlusion-color:#000"';

  const TAGS = ['GRID', 'RADIAL', 'NOISE', 'FLOW', 'ISOMETRIC', 'ORGANIC', 'DISTORTION', 'PHYSICS'];

  const library = (window.patternIndex || []).filter(p => p.frame <= MAX_FRAME_BYTES);
  if (!window.patternIndex) {
    console.error('visuals: no pattern index; run tools/build-pattern-index.py');
  } else {
    console.log('visuals: patterns', library.length, 'of', window.patternIndex.length,
      'whose biggest frame is under', (MAX_FRAME_BYTES / 1e6).toFixed(1) + ' MB');
  }

  function svgDoc(text, wire) {
    const open = text.indexOf('<svg');
    if (open < 0) return null;
    const close = text.indexOf('>', open);
    if (close < 0) return null;   // a truncated file: no opening tag to close
    const head = text.slice(open, close);
    const add = (head.indexOf('xmlns') < 0 ? ' ' + NS : '') + ' ' + (wire ? WIRE : SOLID);
    return text.slice(0, open + 4) + add
      + text.slice(open + 4, close + 1) + RULE + text.slice(close + 1);
  }

  // One frame: fetch the text, rewrite it, decode it through an <img>, and
  // draw it onto an opaque black canvas. The canvas is filled black first
  // rather than left transparent because hydra's blend() mixes rgb and ignores
  // alpha, and a source that is white everywhere with the artwork in its alpha
  // arrives on screen as a white slab; sketches.js says the same thing about
  // the wordmark at smear().
  //
  // The draw is the expensive half and it is synchronous, so it is the thing
  // that gets a frame of its own. The fetch and the decode are not.
  //
  // The coverage readback happens inside the same timed block, deliberately.
  // It is a 64x64 downscale and a getImageData, which forces a flush of
  // everything queued behind it, and leaving it outside meant the `worst
  // frame` figure in the log understated the real stall by the one part of it
  // that has nothing to do with how complicated the artwork is.
  function rasterise(path, wire, done) {
    let xhr;
    try {
      xhr = new XMLHttpRequest();
      xhr.open('GET', BASE + path, true);
    } catch (e) {
      console.error('visuals: pattern open failed', path, e);
      done(null); return;
    }
    xhr.onerror = () => { console.error('visuals: pattern fetch failed', path); done(null); };
    xhr.onload = () => {
      const doc = svgDoc(xhr.responseText || '', wire);
      if (!doc) { console.error('visuals: pattern has no <svg>', path); done(null); return; }
      const url = URL.createObjectURL(new Blob([doc], { type: 'image/svg+xml' }));
      const img = new Image();
      img.onerror = () => {
        URL.revokeObjectURL(url);
        console.error('visuals: pattern decode failed', path);
        done(null);
      };
      // The clock starts at the decode rather than at the draw. Both are on
      // the main thread and for the dense patterns the decode is the larger
      // half; only the XHR is somebody else's thread.
      let t0 = 0, decodeMs = 0;
      img.onload = () => {
        decodeMs = performance.now() - t0;
        requestAnimationFrame(() => {
          const t1 = performance.now();
          let cv = document.createElement('canvas');
          cv.width = SIZE; cv.height = SIZE;
          const ctx = cv.getContext('2d');
          ctx.fillStyle = '#000';
          ctx.fillRect(0, 0, SIZE, SIZE);
          let lit = 0;
          try {
            ctx.drawImage(img, 0, 0, SIZE, SIZE);
            lit = coverage(cv);
          } catch (e) {
            console.error('visuals: pattern draw failed', path, e);
            cv = null;
          }
          URL.revokeObjectURL(url);
          done(cv, decodeMs + (performance.now() - t1), lit);
        });
      };
      t0 = performance.now();
      img.src = url;
    };
    xhr.send();
  }

  // How much of a frame is lit, 0 to 1, as a mean luminance. Drawing the
  // 1024x1024 canvas into a 64x64 one averages it in hardware, so this is 4096
  // pixels read back rather than a million.
  function coverage(cv) {
    const s = 64;
    const small = document.createElement('canvas');
    small.width = s; small.height = s;
    const c = small.getContext('2d', { willReadFrequently: true });
    c.drawImage(cv, 0, 0, s, s);
    const d = c.getImageData(0, 0, s, s).data;
    let sum = 0;
    for (let i = 0; i < d.length; i += 4) {
      sum += 0.2126 * d[i] + 0.7152 * d[i + 1] + 0.0722 * d[i + 2];
    }
    return sum / (255 * s * s);
  }

  // Coverage is telemetry now, not a gate. An earlier version of this file
  // used it to reject a pattern that was a solid sheet at every setting and to
  // trim the degenerate ends off a sweep, on the argument that a frame 40
  // percent lit is not white line work on black. With the strokes at 2.5 px
  // that argument cuts the other way: the reference this show is built against
  // is dense white line work, and a rule tuned against hairlines was throwing
  // away ten patterns and eighteen sweep ends for being what the show wants.
  // The `lit` figures still go in the log, because they are the cheapest way
  // to see what the artwork is doing on a box nobody is standing in front of.
  //
  // What that does leave is the genuinely degenerate end of a slider, where
  // the artwork is 25 specks on black. That is now on screen, and it is the
  // one thing about the morph a viewer might call a bug.

  // The value of the brightest one percent of a frame, 0 to 255, over the
  // largest of the three channels rather than their luminance, because a
  // tinted line is still a lit line. This is the check that the stroke rule
  // above is working: a frame of half-pixel hairlines answers about 130, the
  // same artwork at 2.5 px answers 255. It reads a quarter of a million
  // pixels, which is why it runs once per pattern, on the default frame, and
  // not once per frame.
  function peak99(cv) {
    const d = cv.getContext('2d').getImageData(0, 0, SIZE, SIZE).data;
    const hist = new Uint32Array(256);
    let n = 0;
    for (let i = 0; i < d.length; i += 16) {
      hist[Math.max(d[i], d[i + 1], d[i + 2])] += 1;
      n += 1;
    }
    const cut = Math.max(1, Math.ceil(n * 0.01));
    let acc = 0;
    for (let v = 255; v >= 0; v--) {
      acc += hist[v];
      if (acc >= cut) return v;
    }
    return 0;
  }

  // 1x1, not dropped on the floor. A 1024x1024 backing store is not a JS
  // object and the heap is in no hurry about it, so every path that gives up
  // on a set of frames says so explicitly: the eviction in trim(), and the
  // partial load below, which would otherwise leave up to six full frames
  // behind on a fetch that failed on the seventh.
  function freeFrames(entry) {
    entry.frames.forEach(cv => { if (cv) { cv.width = 1; cv.height = 1; } });
  }

  // Seven frames, strictly one after another, so two patterns are never
  // rasterising into the same animation frames.
  function load(meta, done) {
    const entry = {
      meta: meta, frames: new Array(7), busy: true, ms: 0, worst: 0, peak: 0,
      cover: [], shownAt: 0, at: performance.now(), held: 0
    };
    let i = 0;
    (function step() {
      if (i >= 7) {
        const t0 = performance.now();
        entry.peak = peak99(entry.frames[6]);
        entry.ms += performance.now() - t0;
        entry.busy = false;
        done(entry);
        return;
      }
      rasterise(meta.frames[i], meta.wire, (cv, ms, lit) => {
        if (!cv) {
          entry.busy = false;
          freeFrames(entry);
          done(null);
          return;
        }
        entry.frames[i] = cv;
        entry.cover[i] = lit;
        entry.ms += ms;
        entry.worst = Math.max(entry.worst, ms);
        i += 1;
        step();
      });
    })();
  }

  const cache = [];
  // Slugs shown, most recent last: `recent` is the last RECENT of them and is
  // what take() steers around, `seen` is every one this session and is what
  // the prewarm steers around. They are separate because they answer
  // different questions. take() is choosing between three things in memory
  // and only needs to know which of them the room has just watched; the
  // prewarm is choosing between 49 files and should be pulling in something
  // the room has never seen at all.
  const recent = [];
  const seen = [];
  const rejected = [];   // slugs whose load failed; never retried this session
  let loading = false;
  let tagTurn = 0;

  function cached(slug) {
    return cache.some(e => e.meta.slug === slug) || rejected.indexOf(slug) >= 0;
  }

  function pickFrom(pool) {
    return pool.length ? pool[Math.floor(Math.random() * pool.length)] : null;
  }

  // Round robin over the tag groups, so a run of prewarms cannot land three
  // grids in a row just because GRID is 21 of the 54 patterns, and inside a
  // group prefer something never shown this session over something that has
  // been round already. Falling back twice: first to a pattern that has been
  // shown before, then to any tag at all, because a prewarm that declines to
  // load anything leaves the family with whatever it already has.
  function pickPrewarm() {
    for (let n = 0; n < TAGS.length; n++) {
      const tag = TAGS[(tagTurn + n) % TAGS.length];
      const pool = library.filter(p => p.tags.indexOf(tag) >= 0 && !cached(p.slug));
      const fresh = pool.filter(p => seen.indexOf(p.slug) < 0);
      const pick = pickFrom(fresh.length ? fresh : pool);
      if (pick) {
        tagTurn = (tagTurn + n + 1) % TAGS.length;
        return pick;
      }
    }
    const any = library.filter(p => !cached(p.slug));
    const fresh = any.filter(p => seen.indexOf(p.slug) < 0);
    return pickFrom(fresh.length ? fresh : any);
  }

  // Least recently shown first, and never one a sketch is currently drawing.
  function trim(limit) {
    const age = (e) => Math.max(e.shownAt, e.at);
    while (cache.length > limit) {
      let worst = -1;
      for (let i = 0; i < cache.length; i++) {
        if (cache[i].held || cache[i].busy) continue;
        if (worst < 0 || age(cache[i]) < age(cache[worst])) worst = i;
      }
      if (worst < 0) return;
      const gone = cache.splice(worst, 1)[0];
      freeFrames(gone);
      console.log('visuals: pattern evicted', gone.meta.slug);
    }
  }

  // Room in the cache, or a resident nobody has looked at for ROTATE_MS.
  //
  // One replacement per ROTATE_MS and no more. Without that clause a full
  // cache whose entries are all stale swaps one out every PREWARM_MS until
  // every one of them is new, and a run of three loads back to back is
  // measurable: the page dropped from 23 rendered frames a second to between
  // 12 and 17 while it was happening, and one smoothness sample taken across
  // it came out at four times the sketch's own figure.
  let lastSwapAt = 0;
  function hasRoom() {
    if (cache.length < CACHE_MAX) return true;
    const now = performance.now();
    if (now - lastSwapAt < ROTATE_MS) return false;
    return cache.some(e => !e.busy && !e.held && now - Math.max(e.shownAt, e.at) > ROTATE_MS);
  }

  // A load that never calls back would otherwise retire the whole family for
  // the session, because `loading` gates every later prewarm and nothing else
  // clears it. XMLHttpRequest on file:// has no timeout that can be relied on
  // and neither has image decoding, so the guard is a plain timer and a
  // generation counter: the abandoned load's callbacks, if they ever arrive,
  // see a stale generation and free what they built rather than joining the
  // cache behind the one that replaced them.
  const LOAD_TIMEOUT_MS = 60000;
  let generation = 0;

  function prewarm() {
    if (loading || !hasRoom()) return;
    const meta = pickPrewarm();
    if (!meta) return;
    loading = true;
    // Evict before allocating, not after. Pushing a fourth entry and trimming
    // afterwards is a second or two of four patterns in memory, 117 MB rather
    // than 88, at exactly the moment the page is also decoding an SVG.
    trim(CACHE_MAX - 1);
    if (cache.length >= CACHE_MAX - 1) lastSwapAt = performance.now();
    const t0 = performance.now();
    const mine = ++generation;
    const watchdog = setTimeout(() => {
      if (generation !== mine) return;
      generation += 1;
      loading = false;
      console.log('visuals: pattern load timed out', meta.slug);
    }, LOAD_TIMEOUT_MS);
    load(meta, (entry) => {
      if (generation !== mine) {
        if (entry) freeFrames(entry);
        return;
      }
      clearTimeout(watchdog);
      loading = false;
      if (!entry) {
        rejected.push(meta.slug);
        console.log('visuals: pattern load failed', meta.slug);
        return;
      }
      cache.push(entry);
      trim(CACHE_MAX);
      console.log('visuals: pattern ready', meta.slug,
        (performance.now() - t0).toFixed(0) + ' ms total,',
        entry.ms.toFixed(0) + ' ms on the main thread,',
        'worst frame ' + entry.worst.toFixed(0) + ' ms,',
        'peak ' + entry.peak + ',',
        'lit ' + entry.cover.slice(0, 6).map(c => (100 * c).toFixed(1)).join('/') + '%,',
        (meta.frame / 1e6).toFixed(2) + ' MB in its biggest frame');
    });
  }
  setInterval(prewarm, PREWARM_MS);
  prewarm();

  // The sweep clock. A full traverse of the six frames takes about 40 s when
  // the room is quiet and about 12 s when it is loud, and the position is
  // 2.5 + 2.5 sin(phase), so the pattern breathes through its parameter and
  // back rather than snapping round at the end. Like flow() in sketches.js
  // this integrates a rate rather than multiplying a clock: multiplying an
  // absolute time by feed.energy walks the picture backwards every time the
  // room gets quieter.
  //
  // The swell then pushes the position toward the top of the sweep, so a loud
  // passage sits in the dense half of the parameter and a break sits in the
  // sparse half. It is applied to the 0..1 position and pulls toward 1, which
  // cannot take the result out of range whatever the swell does.
  let phase = 0, phaseAt = performance.now();
  function sweepTick() {
    const now = performance.now();
    const dt = Math.min(100, now - phaseAt);
    phaseAt = now;
    const energy = window.feed ? feed.energy : 0;
    phase += Math.PI * dt / (40000 - 28000 * energy);
    if (phase > 2 * Math.PI) phase -= 2 * Math.PI;
    requestAnimationFrame(sweepTick);
  }
  requestAnimationFrame(sweepTick);

  function sweepT() {
    const u = 0.5 * (1 + Math.sin(phase));
    const swell = window.feed ? feed.swell : 0;
    return 5 * (u + 0.35 * swell * (1 - u));
  }

  // Two slots, so a sketch can hold two patterns at once: slot 0 is s4 and s5,
  // slot 1 is s6 and s7. The melt owns s3 and sketches own nothing below s4.
  const slots = [
    { a: null, b: null, entry: null, i0: -1, i1: -1 },
    { a: null, b: null, entry: null, i0: -1, i1: -1 }
  ];
  const mix = [0, 0];

  // init() builds a fresh regl texture and drops the old one on the floor, so
  // the previous one is destroyed here by hand. Without this a set's worth of
  // frame changes, one every two to four seconds, is a few gigabytes of GPU
  // memory nobody ever asked for.
  function upload(source, canvas) {
    // A canvas an eviction has already shrunk is not a frame. Leaving the
    // previous texture bound shows a stale frame, which is a morph that
    // pauses; uploading a 1x1 would fill the screen with one pixel of it.
    if (!source || !canvas || canvas.width !== SIZE) return;
    try { if (source.tex && source.tex.destroy) source.tex.destroy(); } catch (e) { /* regl kept it */ }
    source.init({ src: canvas, dynamic: false });
  }

  function bindFrames(entry, i0, i1, f, slot) {
    slot = slot ? 1 : 0;
    mix[slot] = Math.max(0, Math.min(1, f));
    if (!entry || entry.busy) return;
    const st = slots[slot];
    if (st.entry === entry && st.i0 === i0 && st.i1 === i1) return;
    const sa = slot ? (window.s6 || null) : (window.s4 || null);
    const sb = slot ? (window.s7 || null) : (window.s5 || null);
    upload(sa, entry.frames[i0]);
    upload(sb, entry.frames[i1]);
    if (st.entry && st.entry !== entry) st.entry.held -= 1;
    if (st.entry !== entry) entry.held += 1;
    st.entry = entry; st.i0 = i0; st.i1 = i1;
  }

  window.patterns = {
    mix: mix,
    count: library.length,

    ready() {
      return cache.some(e => !e.busy);
    },

    // A ready pattern, preferring one the room has not just seen, then one
    // whose tags meet any of `tags`. Never blocks, never rasterises, and
    // returns null only when nothing has finished loading.
    //
    // The order of those two preferences is the fix for what the first
    // version did. It sorted by tag first and by last-shown second, and with
    // three patterns in the cache against eight tag groups the tag filter
    // usually picked out exactly one entry, which then came up under sketch
    // after sketch: four of the eight screenshots taken of this family were
    // the same artwork. Freshness first means a run of pattern sketches walks
    // the cache, and the tag is what chooses between equally fresh ones.
    take(tags, exclude) {
      const pool = cache.filter(e => !e.busy && e !== exclude);
      if (!pool.length) return null;
      const unshown = pool.filter(e => recent.indexOf(e.meta.slug) < 0);
      const from = unshown.length ? unshown : pool;
      const want = (tags || []).length
        ? from.filter(e => e.meta.tags.some(t => tags.indexOf(t) >= 0))
        : [];
      const final = want.length ? want : from;
      final.sort((x, y) => x.shownAt - y.shownAt);
      const pick = final[0];
      pick.shownAt = performance.now();
      recent.push(pick.meta.slug);
      while (recent.length > RECENT) recent.shift();
      if (seen.indexOf(pick.meta.slug) < 0) seen.push(pick.meta.slug);
      return pick;
    },

    // 0..5 along the sweep, advancing on its own clock.
    sweepT: sweepT,

    // Put frames floor(t) and ceil(t) on the slot's two sources and record the
    // fraction for the chain's blend(). Only re-uploads when the integer part
    // moves, which is every two to four seconds, not every frame.
    //
    // DEAD_BAND is why the integer part is not simply floor(t). The sweep
    // position is a sine, so it stops and reverses, and it can stop within a
    // hundredth of an integer: every rendered frame the position crosses the
    // boundary is then two texture uploads, 8 MB of them, and a position
    // hovering there does that thirty times a second. Inside the band the
    // pair already bound is kept and the fraction is clamped, which is the
    // same picture, because at the boundary the mix is showing one frame
    // whichever pair it is expressed in.
    bind(entry, t, slot) {
      if (!entry) return;
      const tt = Math.max(0, Math.min(5, t));
      const st = slots[slot ? 1 : 0];
      let i0 = Math.min(4, Math.floor(tt));
      if (st.entry === entry && st.i1 === st.i0 + 1
        && tt > st.i0 - DEAD_BAND && tt < st.i1 + DEAD_BAND) {
        i0 = st.i0;
      }
      bindFrames(entry, i0, i0 + 1, tt - i0, slot);
    },

    // The two ends a sketch might want by name rather than by position: the
    // frame the site's own default settings drew, which is index 6 and is not
    // part of the sweep at all, and the top of the sweep.
    base() { return 6; },
    top() { return 5; },

    // The primitive under bind(), for a sketch that wants two frames that are
    // not neighbours: pattern-melt crossfades the default against the top of
    // the sweep.
    bindFrames: bindFrames,

    // The director calls this on every sketch switch, before run(). A pattern
    // is only protected from eviction while a sketch is drawing it: the bound
    // GPU textures are copies and survive the canvas being freed, so the hold
    // exists for the next bind() and nothing else. Without the release the two
    // slots would pin two of the three cache entries for ever.
    release() {
      slots.forEach(st => {
        if (st.entry) st.entry.held = Math.max(0, st.entry.held - 1);
        st.entry = null; st.i0 = -1; st.i1 = -1;
      });
    },

    // For the load test and the memory measurement.
    stats() {
      return cache.map(e => ({
        slug: e.meta.slug, busy: e.busy, ms: Math.round(e.ms),
        worst: Math.round(e.worst), peak: e.peak,
        lit: e.cover.slice(0, 6).map(c => +(100 * c).toFixed(1)),
        mb: +(e.meta.frame / 1e6).toFixed(2), held: e.held
      }));
    }
  };
})();
