// The video loader: clips off the disk, played into hydra source s8.
//
// What is on disk. assets/video/ holds clips converted by
// tools/prepare-video.py (640x360, 24 fps at most, H.264 main, no audio, a keyframe every
// 2 s) and assets/video/index.js, generated by tools/build-video-index.py,
// which assigns window.videoIndex = [{file, seconds, width, height}]. The
// directory is git-ignored: a clip is usually someone else's film, so clips
// are deployed from the working tree by deploy-skin.sh and never committed.
// A checkout with no clips has no index, this file logs that, and the video
// sketches stay out of the rotation, as the pattern sketches do without
// patterns.
//
// One <video> element, muted, inline and looping, never added to the DOM,
// and one source. s8 belongs to this file: a sketch reads it with src(s8)
// and nothing in sketches.js may init or clear it.
//
// The director opens and closes it, exactly as it opens and closes the
// webcam on s0: open() when a sketch that reads video is about to start and
// the video is not already open, close() when the rotation reaches a sketch
// that reads neither. The Pi 5 has no hardware H.264 decoder, so a playing
// clip costs CPU beside Mixxx's audio engine, and a closed one costs
// nothing: close() pauses the element, drops its src so the decoder is torn
// down, and puts a 1x1 blank back on s8.
//
// open() picks a clip at random and a start point at random, leaving the
// last 10 s out so a clip does not loop straight back to its start the
// moment it comes up. A clip that fails to load, seek or play is logged,
// set aside for the rest of the session, and another one is tried; when
// none is left, available() goes false, the video sketches drop out of the
// rotation, and the director is told so it can move off a sketch that was
// drawing it.
//
// Seeking needs the server to answer HTTP Range requests. On the Pi the page
// is a file:// URL and seeking works. `python -m http.server`, which serves
// the desktop preview, does not answer Range, and Chrome cannot seek a video
// served without it: the seek either never completes or lands back at 0. A
// seek that has not landed within SEEK_TIMEOUT_MS, or that lands more than a
// second away from where it was sent, is logged and the clip plays from
// where it is instead. That is not a failure and does not set the clip aside.
(function () {
  const BASE = 'assets/video/';
  const TAIL_S = 10;              // no start point in the last 10 s of a clip
  const SEEK_TIMEOUT_MS = 3000;   // a seek that has not landed by now will not
  const LOAD_TIMEOUT_MS = 15000;  // metadata or a first frame this late is a failure

  const index = Array.isArray(window.videoIndex) ? window.videoIndex : null;
  if (!index) {
    console.log('visuals: no video index; run tools/prepare-video.py and tools/build-video-index.py');
  } else {
    console.log('visuals: video', index.length, index.length === 1 ? 'clip' : 'clips');
  }
  const clips = index || [];
  const failed = new Set();

  const el = document.createElement('video');
  el.muted = true;
  el.defaultMuted = true;
  el.playsInline = true;
  el.loop = true;
  el.preload = 'auto';

  // `wanted` is true from open() until close(); `playing` only once a frame
  // has been decoded and s8 holds it. `gen` counts opens, and every async
  // step checks it, so a close() or a second open() in the middle of a load
  // stops the first one where it is.
  let wanted = false, playing = false, gen = 0, file = null;
  let giveUpHook = null;

  function candidates() {
    return clips.filter(c => !failed.has(c.file));
  }

  // s8's texture is replaced on every open and every close, and
  // HydraSource.init and .clear both allocate a new regl texture without
  // destroying the old one (vendor/hydra-synth.js, HydraSource), so each is
  // destroyed here first. At 640x360 that is about 0.9 MB a cycle otherwise.
  function dropTexture() {
    try { s8.tex.destroy(); } catch (e) { /* already gone */ }
  }

  function unload() {
    el.pause();
    el.removeAttribute('src');
    // load() with no src is what makes Chromium release the decoder; a
    // paused element with a src keeps it.
    el.load();
  }

  // Resolves when `ev` fires on the element, rejects on an error event or
  // after `ms`. The listeners are removed either way.
  function waitFor(ev, ms) {
    return new Promise((resolve, reject) => {
      const done = (fn, v) => {
        clearTimeout(timer);
        el.removeEventListener(ev, onEv);
        el.removeEventListener('error', onErr);
        fn(v);
      };
      const onEv = () => done(resolve);
      const onErr = () => done(reject, new Error(el.error ? 'media error ' + el.error.code
        + (el.error.message ? ' ' + el.error.message : '') : 'media error'));
      const timer = setTimeout(() => done(reject, new Error('no ' + ev + ' after ' + ms + ' ms')), ms);
      el.addEventListener(ev, onEv);
      el.addEventListener('error', onErr);
    });
  }

  function load(my) {
    const list = candidates();
    if (!list.length) {
      wanted = false;
      console.log('visuals: video unavailable, every clip has failed this session');
      if (giveUpHook) {
        try { giveUpHook(); } catch (e) { console.error('visuals: video give-up hook failed', e); }
      }
      return;
    }
    const clip = list[Math.floor(Math.random() * list.length)];
    const stale = () => my !== gen;
    el.src = BASE + clip.file;
    waitFor('loadedmetadata', LOAD_TIMEOUT_MS).then(() => {
      if (stale()) return null;
      const dur = isFinite(el.duration) && el.duration > 0 ? el.duration : clip.seconds;
      const start = Math.max(0, dur - TAIL_S) * Math.random();
      if (start < 1) return 0;
      el.currentTime = start;
      return waitFor('seeked', SEEK_TIMEOUT_MS).then(() => {
        if (Math.abs(el.currentTime - start) > 1) {
          console.log('visuals: video seek to', start.toFixed(1), 's landed at',
            el.currentTime.toFixed(1), 's; the server does not answer Range requests, playing from there');
        }
        return el.currentTime;
      }, (e) => {
        if (el.error) throw e;
        console.log('visuals: video seek to', start.toFixed(1), 's did not land (' + e.message
          + '); the server does not answer Range requests, playing from', el.currentTime.toFixed(1), 's');
        return el.currentTime;
      });
    }).then((from) => {
      if (stale() || from === null) return null;
      const first = el.readyState >= 2 ? Promise.resolve() : waitFor('loadeddata', LOAD_TIMEOUT_MS);
      return first.then(() => el.play()).then(() => from);
    }).then((from) => {
      if (stale() || from === null) return;
      // A frame is decodable now (readyState 2 or more), so the texture can be
      // built from the element; building it from an element with no frame
      // gives regl a 0x0 source.
      dropTexture();
      s8.init({ src: el, dynamic: true });
      playing = true;
      file = clip.file;
      console.log('visuals: video', clip.file, 'from', from.toFixed(1), 's');
    }).catch((e) => {
      if (stale()) return;
      failed.add(clip.file);
      console.error('visuals: video ' + clip.file + ' failed: '
        + (e && e.message ? e.message : String(e)) + '; set aside for the session');
      unload();
      load(my);
    });
  }

  window.video = {
    // A clip exists and not every clip has failed. director.js gates the
    // video sketches on this and asks for the video for a vidMix sketch only
    // while it is true.
    available() { return candidates().length > 0; },
    // A clip is loaded, playing and on s8.
    ready() { return playing; },
    // open() has been called and close() has not: the sketch being started
    // will get footage, now or a few frames from now. The vidMix helpers in
    // sketches.js build their mix on this, because run() comes before the
    // first frame is decoded.
    isOpen() { return wanted; },
    // The clip on s8, or null. preview.js shows it.
    file() { return playing ? file : null; },
    open() {
      if (wanted) return;
      if (!this.available()) return;
      wanted = true;
      gen += 1;
      load(gen);
    },
    close() {
      if (!wanted && !playing) return;
      wanted = false;
      playing = false;
      file = null;
      gen += 1;
      unload();
      dropTexture();
      s8.clear();
      console.log('visuals: video closed');
    },
    // director.js registers one function, called when the last clip fails.
    onGiveUp(fn) { giveUpHook = typeof fn === 'function' ? fn : null; },
    failed() { return Array.from(failed); }
  };
})();
