// The video loader: clips off the disk, played into hydra source s8.
//
// What is on disk. assets/video/ holds clips converted by
// tools/prepare-video.py (640x360, 24 fps at most, H.264 main, no audio, a keyframe every
// 2 s) and assets/video/index.js, generated by tools/build-video-index.py,
// which assigns window.videoIndex = [{file, seconds, width, height}]. The
// directory is git-ignored: a clip is usually someone else's film, so clips
// are deployed from the working tree by deploy-skin.sh and never committed.
// A checkout with no clips has no index, this file logs that, and the video
// sketches stay out of the rotation, as the pattern sketches do without
// patterns. Clips uploaded through the admin page live outside the deployed
// tree, in ~/bitedj-media/video/, listed in its own index.json; the list here
// is the two merged, a deployed clip winning a name clash, reread every 30 s
// so an upload reaches the TV without a reload.
//
// One <video> element, muted, inline and looping, never added to the DOM,
// and one source. s8 belongs to this file: a sketch reads it with src(s8)
// and nothing in sketches.js may init or clear it.
//
// The director opens and closes it, exactly as it opens and closes the
// webcam on s0: open() when a sketch that reads video is about to start and
// the video is not already open, close() when the rotation reaches a sketch
// that reads neither. The Pi 5 has no hardware H.264 decoder, so a playing
// clip costs CPU beside Mixxx's audio engine, and a closed one costs
// nothing: close() pauses the element, drops its src so the decoder is torn
// down, and puts a 1x1 blank back on s8.
//
// open() picks a clip at random and a start point at random, leaving the
// last 10 s out so a clip does not loop straight back to its start the
// moment it comes up. A clip that fails to load, seek or play is logged,
// set aside for the rest of the session, and another one is tried; when
// none is left, available() goes false, the video sketches drop out of the
// rotation, and the director is told so it can move off a sketch that was
// drawing it. open(file) plays that clip from its start instead, and
// pin(file), which only preview mode calls, makes every plain open() do the
// same.
//
// Seeking needs the server to answer HTTP Range requests. On the Pi the page
// is a file:// URL and seeking works. `python -m http.server`, which serves
// the desktop preview, does not answer Range, and Chrome cannot seek a video
// served without it: the seek either never completes or lands back at 0. A
// seek that has not landed within SEEK_TIMEOUT_MS, or that lands more than a
// second away from where it was sent, is logged and the clip plays from
// where it is instead. That is not a failure and does not set the clip aside.
(function () {
  const BASE = 'assets/video/';
  const TAIL_S = 10;              // no start point in the last 10 s of a clip
  const SEEK_TIMEOUT_MS = 3000;   // a seek that has not landed by now will not
  const LOAD_TIMEOUT_MS = 15000;  // metadata or a first frame this late is a failure
  const REFRESH_MS = 30000;       // how often the uploads' index is reread

  const index = Array.isArray(window.videoIndex) ? window.videoIndex : null;
  if (!index) {
    console.log('visuals: no video index; run tools/prepare-video.py and tools/build-video-index.py');
  } else {
    console.log('visuals: video', index.length, index.length === 1 ? 'clip' : 'clips');
  }
  const deployed = (index || []).map(c => ({ file: c.file, seconds: c.seconds, src: BASE + c.file, source: 'deployed' }));
  // Filled by refresh() from ~/bitedj-media/video/index.json.
  let uploaded = [];
  let uploadsNoted = null;        // the last thing said about the uploads, to say it once
  const failed = new Set();
  let pinnedFile = null;

  // Deployed first, in index order, then uploads not shadowed by a deployed
  // clip of the same name. The service never gives an upload a deployed
  // clip's name, so a clash means a deployed clip arrived later; the
  // deployed one is what the PC meant.
  function clips() {
    const names = new Set(deployed.map(c => c.file));
    return deployed.concat(uploaded.filter(c => !names.has(c.file)));
  }

  const setAllows = (file) => !window.sets || sets.allows('clip', file);

  function candidates() {
    return clips().filter(c => !failed.has(c.file) && setAllows(c.file));
  }

  // Rereads the uploads' index. `done`, if given, runs once the read has
  // finished, whatever it found; preview.js waits on it before showing a
  // clip that may exist only as an upload.
  function refresh(done) {
    const finish = () => { if (typeof done === 'function') done(); };
    const paths = window.visualsPaths;
    if (!paths || typeof paths.readText !== 'function') { finish(); return; }
    const dir = paths.media + 'video/';
    paths.readText(dir + 'index.json', (err, text) => {
      if (err) {
        if (uploadsNoted !== 'none') console.log('visuals: no uploaded clips (' + err.message + ')');
        uploadsNoted = 'none';
        uploaded = [];
        finish();
        return;
      }
      let list = null;
      try {
        list = JSON.parse(text);
      } catch (e) {
        // Keep what we had: the service writes the index by rename, so a
        // parse error is a real problem, not a half-written file.
        console.error('visuals: uploaded clip index unreadable:', e.message);
      }
      if (Array.isArray(list)) {
        uploaded = list
          .filter(c => c && typeof c.file === 'string')
          .map(c => ({ file: c.file, seconds: Number(c.seconds) || 0, src: dir + c.file, source: 'uploaded' }));
        const note = String(uploaded.length);
        if (note !== uploadsNoted) console.log('visuals: uploaded clips', uploaded.length);
        uploadsNoted = note;
      }
      finish();
    });
  }

  const el = document.createElement('video');
  el.muted = true;
  el.defaultMuted = true;
  el.playsInline = true;
  el.loop = true;
  el.preload = 'auto';

  // `wanted` is true from open() until close(); `playing` only once a frame
  // has been decoded and s8 holds it. `gen` counts opens, and every async
  // step checks it, so a close() or a second open() in the middle of a load
  // stops the first one where it is.
  let wanted = false, playing = false, gen = 0, file = null;
  let giveUpHook = null;

  // s8's texture is replaced on every open and every close, and
  // HydraSource.init and .clear both allocate a new regl texture without
  // destroying the old one (vendor/hydra-synth.js, HydraSource), so each is
  // destroyed here first. At 640x360 that is about 0.9 MB a cycle otherwise.
  function dropTexture() {
    try { s8.tex.destroy(); } catch (e) { /* already gone */ }
  }

  function unload() {
    el.pause();
    el.removeAttribute('src');
    // load() with no src is what makes Chromium release the decoder; a
    // paused element with a src keeps it.
    el.load();
  }

  // Resolves when `ev` fires on the element, rejects on an error event or
  // after `ms`. The listeners are removed either way.
  function waitFor(ev, ms) {
    return new Promise((resolve, reject) => {
      const done = (fn, v) => {
        clearTimeout(timer);
        el.removeEventListener(ev, onEv);
        el.removeEventListener('error', onErr);
        fn(v);
      };
      const onEv = () => done(resolve);
      const onErr = () => done(reject, new Error(el.error ? 'media error ' + el.error.code
        + (el.error.message ? ' ' + el.error.message : '') : 'media error'));
      const timer = setTimeout(() => done(reject, new Error('no ' + ev + ' after ' + ms + ' ms')), ms);
      el.addEventListener(ev, onEv);
      el.addEventListener('error', onErr);
    });
  }

  // `want` names a clip to play from its start (open(file), or the pin); a
  // clip that is not there or has failed this session is logged and a random
  // allowed one plays instead, so the screen is never left blank for it.
  function load(my, want) {
    let clip = null;
    if (want) {
      clip = clips().find(c => c.file === want && !failed.has(c.file)) || null;
      if (!clip) console.log('visuals: video', want, 'is not available; playing another clip');
    }
    if (!clip) {
      const list = candidates();
      if (!list.length) {
        wanted = false;
        console.log('visuals: video unavailable, every clip has failed this session or none is in the set');
        if (giveUpHook) {
          try { giveUpHook(); } catch (e) { console.error('visuals: video give-up hook failed', e); }
        }
        return;
      }
      clip = list[Math.floor(Math.random() * list.length)];
    }
    const fromStart = !!want && clip.file === want;
    const stale = () => my !== gen;
    // A clip opened over one that is playing (a sequence's video entry after
    // another clip) changes the src of the element s8 is still reading.
    // hydra's HydraSource.tick uploads from it every frame while s8 is
    // dynamic, and until the new clip has a frame each upload is
    // "texSubImage2D: no video"; Chromium reports 32 WebGL errors a page and
    // then none, so a real one later in the night would never be logged.
    // Freeze the texture first: it keeps the old clip's last frame, which is
    // what the screen showed anyway, and the s8.init() below makes it dynamic
    // again once the new clip has a frame. A clip that fails and a give-up
    // leave it frozen, so s8 never reads an element with no src.
    if (window.s8 && s8.src === el) s8.dynamic = false;
    el.src = clip.src;
    waitFor('loadedmetadata', LOAD_TIMEOUT_MS).then(() => {
      if (stale()) return null;
      if (fromStart) return 0;
      const dur = isFinite(el.duration) && el.duration > 0 ? el.duration : clip.seconds;
      const start = Math.max(0, dur - TAIL_S) * Math.random();
      if (start < 1) return 0;
      el.currentTime = start;
      return waitFor('seeked', SEEK_TIMEOUT_MS).then(() => {
        if (Math.abs(el.currentTime - start) > 1) {
          console.log('visuals: video seek to', start.toFixed(1), 's landed at',
            el.currentTime.toFixed(1), 's; the server does not answer Range requests, playing from there');
        }
        return el.currentTime;
      }, (e) => {
        if (el.error) throw e;
        console.log('visuals: video seek to', start.toFixed(1), 's did not land (' + e.message
          + '); the server does not answer Range requests, playing from', el.currentTime.toFixed(1), 's');
        return el.currentTime;
      });
    }).then((from) => {
      if (stale() || from === null) return null;
      const first = el.readyState >= 2 ? Promise.resolve() : waitFor('loadeddata', LOAD_TIMEOUT_MS);
      return first.then(() => el.play()).then(() => from);
    }).then((from) => {
      if (stale() || from === null) return;
      // A frame is decodable now (readyState 2 or more), so the texture can be
      // built from the element; building it from an element with no frame
      // gives regl a 0x0 source.
      dropTexture();
      s8.init({ src: el, dynamic: true });
      playing = true;
      file = clip.file;
      console.log('visuals: video', clip.file, 'from', from.toFixed(1), 's');
    }).catch((e) => {
      if (stale()) return;
      failed.add(clip.file);
      console.error('visuals: video ' + clip.file + ' failed: '
        + (e && e.message ? e.message : String(e)) + '; set aside for the session');
      unload();
      load(my);
    });
  }

  window.video = {
    // A clip the set allows exists and has not failed. director.js gates the
    // video sketches on this and asks for the video for a vidMix sketch only
    // while it is true.
    available() { return candidates().length > 0; },
    // A clip is loaded, playing and on s8.
    ready() { return playing; },
    // open() has been called and close() has not: the sketch being started
    // will get footage, now or a few frames from now. The vidMix helpers in
    // sketches.js build their mix on this, because run() comes before the
    // first frame is decoded.
    isOpen() { return wanted; },
    // The clip on s8, or null. preview.js shows it.
    file() { return playing ? file : null; },
    // Without a file: the pin if there is one, else a random allowed clip at
    // a random point, and nothing at all if one is already open. With a file:
    // that clip from 0, replacing whatever is open.
    open(want) {
      const target = want || pinnedFile;
      if (!want && wanted) return;
      if (!target && !this.available()) return;
      wanted = true;
      playing = false;
      gen += 1;
      load(gen, target || null);
    },
    close() {
      if (!wanted && !playing) return;
      wanted = false;
      playing = false;
      file = null;
      gen += 1;
      unload();
      dropTexture();
      s8.clear();
      console.log('visuals: video closed');
    },
    pin(want) {
      pinnedFile = want || null;
      console.log('visuals: video pin', pinnedFile || 'off');
    },
    refresh: refresh,
    clips: clips,
    // director.js registers one function, called when the last clip fails.
    onGiveUp(fn) { giveUpHook = typeof fn === 'function' ? fn : null; },
    failed() { return Array.from(failed); }
  };

  refresh();
  setInterval(refresh, REFRESH_MS);
})();
